# Usage:
#   Build app image:
#   $ docker compose build
#
#   Run this until it succeeds:
#   $ script/compose-migrate
#
#   Add my user:
#   $ docker compose run --rm app -- bin/rails runner script/seed-spraints
#
#   Prep output:
#   $ docker compose run --rm -u 0 app -- script/setup-mcrouter-path
#
#   Run this to bring the thing up:
#   $ docker compose up
#
#   Open http://127.0.0.1:3080/
#
#   You can add "mc:25565" as a backend. Then, if you add it to a
#   configuration, add its name to /etc/hosts.
services:
  app:
    build: .
    environment:
      RAILS_ENV: "production"
      # SECRET_KEY_BASE can be generated like "ruby -rsecurerandom -e 'puts SecureRandom.hex(64)'
      # or you can set RAILS_MASTER_KEY to the contents of config/credentials/production.key.
      SECRET_KEY_BASE: 9ff768667abbf33ec9bc63783e5dc88b90199ceda00e5022bec2c7e953e3c0b0adc0c0b8a202c6a803df1510111ed61985532816afa178dfe3f1404461bdb40b
      MINECRAFT_MANAGER_DB_HOST: postgres
      MINECRAFT_MANAGER_DB_USERNAME: postgres
      MINECRAFT_MANAGER_DB_PASSWORD: hihihi000
      MINECRAFT_MANAGER_DB_SSLMODE: disable
      MC_ROUTES: "/var/run/mc-router/config/routes.json"
      BACKBURNER_IN_PUMA: "true"
    volumes:
      - "mcrouter:/var/run/mc-router"
    ports:
      - "127.0.0.1:3080:3000"

  mcrouter:
    image: "itzg/mc-router:latest@sha256:4b8fb4a0a035c7a1fa1098a0a1c59554bbbfa5b7558f3901ca21b942744c47f3"
    environment:
      ROUTES_CONFIG: "/var/run/mc-router/config/routes.json"
      ROUTES_CONFIG_WATCH: "true"
      WEBHOOK_URL: "http://app:3000/hook/mcrouter"
    ports:
      - "127.0.0.1:25565:25565"
    volumes:
      - "mcrouter:/var/run/mc-router"

  beanstalk:
    image: clover/beanstalk
    volumes:
      - bs:/var/lib/beanstalkd

  postgres:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: "hihihi000"
    volumes:
      - "pgdata:/var/lib/postgresql"

  mc:
    image: itzg/minecraft-server:latest
    environment:
      EULA: "TRUE"
    ports:
      - "127.0.0.1:25575:25575"
    volumes:
      - "mcdata:/data"

volumes:
  bs:
  mcdata:
  mcrouter:
  pgdata:
